server:
  port: 8001

#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml                        # mybatis配置文件所在路径
#  type-aliases-package: com.yaolong.springcloud.entities            # 所有Entity别名类所在包                                    # mapper映射文件
#  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservicecloud-dept
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://47.94.81.96:3307/cloudDB01                                          # 数据库名称
    username: root
    password: yin7372175240000
    dbcp2:
      min-idle: 5                                                                                                                                 # 数据库连接池的最小维持连接数
      initial-size: 5                                                                                                                     # 初始化连接数
      max-total: 5                                                                                                                              # 最大连接数
      max-wait-millis:   200                                                                                                      # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept:8081
    prefer-ip-address: true